spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleafdb?serverTimezone=UTC
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8081